backtrack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tracker.urls')),
    path('admin/', admin.site.urls),
    
]

tracker/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from tracker.views import home, signup, signout, groupform
from tracker.views import StudentList, StudentCreate, StudentDelete, StudentUpdate, StudentDetail
from tracker.views import AssessmentList, AssessmentCreate, AssessmentDelete, AssessmentUpdate, StandardDetail
from tracker.views import StandardCreate, StandardList, StandardDelete, StandardUpdate, AssessmentDetail
from tracker.views import reverse, reverse_lazy



urlpatterns = [
    path('', home, name='home'),
    path('login/', LoginView.as_view(template_name = 'login.html'), name="login"),
    path('signup/', signup, name='signup'),
    path('signout/', signout, name='signout'),
    path('students/', StudentList.as_view(), name='student-list'),
    path('student/add/', StudentCreate.as_view(), name ='student-add'),
    path('student/<int:pk>/', StudentUpdate.as_view(), name ='student-update'),
    path('student/<int:pk>/delete/', StudentDelete.as_view(), name ='student-delete'),
    path('students/<int:pk>/', StudentDetail.as_view(), name="student-detail"),
    path('standards/', StandardList.as_view(), name='standard-list'),
    path('standard/add/', StandardCreate.as_view(), name ='standard-add'),
    path('standard/<int:pk>/', StandardUpdate.as_view(), name ='standard-update'),
    path('standard/<int:pk>/delete/', StandardDelete.as_view(), name ='standard-delete'),
    path('standards/<int:pk>/', StandardDetail.as_view(), name="standard-detail"),
    path('assessments/', AssessmentList.as_view(), name='assessment-list'),
    path('assessment/add/', AssessmentCreate.as_view(), name ='assessment-add'),
    path('assessment/<int:pk>/', AssessmentUpdate.as_view(), name ='assessment-update'),
    path('assessment/<int:pk>/delete/', AssessmentDelete.as_view(), name ='assessment-delete'),
    path('assessments/<int:pk>/', AssessmentDetail.as_view(), name="assessment-detail"),
    path('groups/', groupform, name='group-form'),
]

tracker/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm

class TimestampedBaseModel(models.Model):
    class Meta:
        abstract = True

    created_at = models.DateTimeField(editable=False)
    updated_at = models.DateTimeField()

    def save(self, *args, **kwargs):
        """ On save, update timestamps """
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super(TimestampedBaseModel, self).save(*args, **kwargs)

    def __str__(self):
        str_data = []
        if self.id:
            str_data.append(str(self.id))
        if hasattr(self, "uuid"):
            str_data.append(str(self.uuid))
        if hasattr(self, "name"):
            str_data.append(self.name)
        return " / ".join(str_data)

class Student(TimestampedBaseModel):
    active = models.BooleanField(default=True)
    first_name = models.CharField(max_length=50, null=False, blank=False)
    last_name = models.CharField(max_length=50, null=False, blank=False)
   

    def __str__(self):
        return f" {self.first_name} {self.last_name}"

    
    def get_absolute_url(self):
        return reverse('student-detail', kwargs={'pk': self.pk})
 

class Standard(TimestampedBaseModel):
    active = models.BooleanField(default=True)
    statement_name = models.CharField(max_length=200, null=False, blank=False)

    def get_absolute_url(self):
        return reverse('standard-detail', kwargs={'pk': self.pk})
    
    def __str__(self):
        return f" {self.statement_name}"

SEMESTER_CHOICES = ( 
    ("BOY", "BOY"), 
    ("MOY", "MOY"), 
    ("EOY", "EOY"), 
)

class Assessment(TimestampedBaseModel):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE)
    score = models.IntegerField(null = False)
    semester = models.CharField( 
        max_length = 20, 
        choices = SEMESTER_CHOICES, 
        default = 'BOY'
    ) 

    def save(self, *args, **kwargs):
        if self.score < 1 or self.score > 4:
            raise ValueError("score must between 1 and 4 inclusive")
        return super(Assessment, self).save(*args, **kwargs)
    

    def get_absolute_url(self):
        return reverse('assessment-detail', kwargs={'pk': self.pk})

tracker/forms.py
from django import forms
from tracker.models import Student
from tracker.models import Assessment
from tracker.models import Standard

class GroupForm(forms.Form):
    numbergroups = forms.IntegerField(label='Number of Groups', min_value=1)
    
    selected_standards = forms.ModelMultipleChoiceField(label='Select Standards (Hold Command to Select Multiple)', queryset=Standard.objects.all())

tracker/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView
from django.urls import reverse, reverse_lazy
from tracker.models import Student, Standard, Assessment
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView    
from django.http import HttpResponseRedirect
from django.shortcuts import render
from tracker.groups import ResolveGroups
from tracker.forms import GroupForm

def signup(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('home')
        else:
            return render(request, 'signup.html', {'form': form})
    else:
        form = UserCreationForm()
        return render(request, 'signup.html', {'form': form})

def signout(request):
    logout(request)
    return redirect('home')

def home(request):
    return render(request, "home.html")

def groupform(request):
    form = GroupForm(request.GET)
    context = {
        'form': form
    }
    if form.is_valid(): 
        print(form.cleaned_data['selected_standards'], form.cleaned_data['numbergroups'])
        context["sorted_students"] = ResolveGroups(form.cleaned_data['numbergroups'], form.cleaned_data['selected_standards'])

    return render(request, 'groups.html', context)

class StudentList(LoginRequiredMixin, ListView):
    model = Student


class StudentCreate(LoginRequiredMixin, CreateView):
    model = Student
    fields = ['active', 'first_name', 'last_name']


class StudentUpdate(LoginRequiredMixin, UpdateView):
    model = Student
    fields = ['active', 'first_name', 'last_name']


class StudentDelete(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy('student-list')

class StudentDetail(LoginRequiredMixin, DetailView):
    model = Student
    fields = ['active', 'first_name', 'last_name', 'statement_name', 'score', 'semester']


class StandardList (LoginRequiredMixin, ListView):
    model = Standard


class StandardCreate(LoginRequiredMixin, CreateView):
    model = Standard
    fields = ['active', 'statement_name']


class StandardUpdate(LoginRequiredMixin, UpdateView):
    model = Standard
    fields = ['active', 'statement_name']


class StandardDelete(LoginRequiredMixin, DeleteView):
    model = Standard
    success_url = reverse_lazy('standard-list')

class StandardDetail(LoginRequiredMixin, DetailView):
    model = Standard


class AssessmentList (LoginRequiredMixin, ListView):
    model = Assessment


class AssessmentCreate(LoginRequiredMixin, CreateView):
    model = Assessment
    fields = ['student', 'standard', 'score', "semester"]


class AssessmentUpdate(LoginRequiredMixin, UpdateView):
    model = Assessment
    fields = ['student', 'standard', 'score', "semester"]


class AssessmentDelete(LoginRequiredMixin, DeleteView):
    model = Assessment
    success_url = reverse_lazy('assessment-list')

class AssessmentDetail(LoginRequiredMixin, DetailView):
    model = Assessment


def load_standards(request):
    standard = Standards.objects.all().order_by('standard__statement')
    return render(request, 'hr/grou_form.html', {'standard': standard})

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
  <title>Sarah Tracker</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
</head>

<body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url "home" %}"> Student Tracker</a></h5>
   {% block nav_links%}
   {% if user.is_authenticated %}
    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-dark" href="{% url "student-list" %}">Students</a>
      <a class="p-2 text-dark" href="{% url "standard-list" %}">Standards</a>
      <a class="p-2 text-dark" href="{% url "assessment-list" %}">Assessments</a>
      <a class="p-2 text-dark" href="{% url "group-form" %}">Groups</a>
    </nav>
    {% endif %}
    <div>
      {% if user.is_authenticated %}
        <a href="{% url "signout" %}" class="btn btn-primary btn-sm ml-2">
          Sign Out
          </a>
      {% else %}
      <a href="{% url "signup" %}" class="btn btn-primary btn-sm ml-2">
        Sign Up
        </a>
      <a href="{% url "login" %}" class="btn btn-success btn-sm ml-2">
        Login
        </a>
      {% endif %}
    </div>
    {% endblock%}
    <!--<a class="btn btn-outline-primary" href="#">Sign up</a>-->
  </div>
  <div class="container">{% block content%}{% endblock%} </div>

</body>

</html>

templates/groups.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<form action="/groups/" method="GET">
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary" value="Submit">Submit</button>
</form>
<hr />
{% if sorted_students %}
{% for item in sorted_students %} 
<p>Group: {{item.group_id}}: {{item.student}}, Average Score: {{item.score}}</p>
    {% endfor %}
    {% endif %}
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<main role="main" class="container bg-info">
    <div class="jumbotron bg-info">
      <h1 class="text-white">Welcome!</h1>
      <p class="lead text-white">You can now view your class's progress and make groups easier than ever before!</p>
      <a class="btn btn-lg btn-dark" href="{% url "student-list" %}" role="button">Go To Your Class &raquo;</a>
    </div>
</main>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<h2>Log In</h2>
<form method="post">
 {% csrf_token %}
 {% bootstrap_form form %}
 <button type="submit">Log In</button>
</form>
{% endblock %}

templates/signout.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit">Sign up</button>
</form>
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
 {% bootstrap_form form %}
  <button type="submit">Sign up</button>
</form>
{% endblock %}

templates/tracker/assessment_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete this assessment "{{ object }}"?</p>
    <input type="submit" value="Confirm Deletion">
</form>
<div class="btn-group">
    <a href="{% url "assessment-list" %}" class="btn btn-primary mt-2">
        Cancel
    </a>
</div>
{% endblock %}

templates/tracker/assessment_detail.html
{% extends "base.html" %}
{% block content %}
<div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Standard: {{object.standard.statement_name}}</li>
      <li class="list-group-item">Student: {{object.student.first_name}} {{object.student.last_name}}</li>
      <li class="list-group-item">Score: {{object.score}}</li>
      <li class="list-group-item">Semester: {{object.semester}}</li>
    </ul>
</div>
<p>
    Active: {{object.active}}
</p>
<div class="btn-group">
    <a href="{% url "assessment-list" %}" class="btn btn-primary btn-sm ml-2">
        Go Back to Assessment List
    </a>
    <a href="{% url "assessment-update" pk=object.pk %}" class="btn btn-warning btn-sm ml-2">
        Edit Assessment
    </a>
    <a href="{% url "assessment-delete" pk=object.pk %}" class="btn btn-danger btn-sm ml-2">
        Delete Assessment
    </a>
</div>
{% endblock %}

templates/tracker/assessment_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">
        Save
    </button>
</form>
{% endblock %}

templates/tracker/assessment_list.html
{% extends "base.html" %}
{% block content %}
<h2>Assessments</h2>

<a class="btn btn-success btn-sm mb-3" href="{% url "assessment-add" %}" role="button">
    Create New Assessment
    <i class="bi bi-person-plus"></i>
</a>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Standard</th>
            <th scope="col">Student First</th>
            <th scope="col">Student Last</th>
            <th scope="col">Score</th>
            <th scope="col">Semester</th>
        </tr>
    </thead>
    <tbody>
        {% for assessment in object_list %}
        <tr>
            <th scope="row">
                <a href="{% url "assessment-detail" pk=assessment.pk %}">
                    {{assessment.id}}
                </a>
            </th>
            <td>
                <a href="{% url "assessment-detail" pk=assessment.pk %}">
                    {{assessment.standard.statement_name}}
                </a>
            </td>
            <td>
                <a href="{% url "assessment-detail" pk=assessment.pk %}">
                    {{assessment.student.first_name}}
                </a>
            </td>
            <td>
                <a href="{% url "assessment-detail" pk=assessment.pk %}">
                    {{assessment.student.last_name}}
                </a>
            </td>
            <td>
                <a href="{% url "assessment-detail" pk=assessment.pk %}">
                    {{assessment.score}}
                </a>
            </td>
            <td>
                <a href="{% url "assessment-detail" pk=assessment.pk %}">
                    {{assessment.semester}}
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/tracker/standard_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete this standard? "{{ object }}"?</p>
    <input type="submit" value="Confirm Deletion">
</form>
<div class="btn-group">
    <a href="{% url "standard-list" %}" class="btn btn-primary mt-2">
        Cancel
    </a>
</div>
{% endblock %}

templates/tracker/standard_detail.html
{% extends "base.html" %}
{% block content %}
<h1>
    <small>
        Standard: {{object.statement_name}}
    </small>
</h1>
<p>
    Active: {{object.active}}
</p>
<div class="btn-group">
    <a href="{% url "standard-list" %}" class="btn btn-primary btn-sm ml-2">
        Go Back to Standards List
    </a>
    <a href="{% url "standard-update" pk=object.pk %}" class="btn btn-warning btn-sm ml-2">
        Edit Standards
    </a>
    <a href="{% url "standard-delete" pk=object.pk %}" class="btn btn-danger btn-sm ml-2">
        Delete Standards
    </a>
</div>
{% endblock %}

templates/tracker/standard_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">
        Save
    </button>
</form>
{% endblock %}

templates/tracker/standard_list.html
{% extends "base.html" %}
{% block content %}
<h2>Standards</h2>
<a class="btn btn-success btn-sm mb-3" href="{% url "standard-add" %}" role="button">
  Create A New Standard
  <i class="bi bi-plus-circle"></i>
</a>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Standard</th>
    </tr>
  </thead>
  <tbody>
    {% for standard in object_list %}
    <tr>
      <th scope="row">
        <a href="{% url "standard-detail" pk=standard.pk %}">
          {{standard.id}}
        </a>
      </th>
      <td>
        <a href="{% url "standard-detail" pk=standard.pk %}">
          {{standard.statement_name}}
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/tracker/student_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete this student "{{ object }}"?</p>
    <input type="submit" value="Confirm Deletion">
</form>
<div class="btn-group">
    <a href="{% url "assessment-list" %}" class="btn btn-primary mt-2">
        Cancel
    </a>
</div>
{% endblock %}

templates/tracker/student_detail.html
{% extends "base.html" %}
{% block content %}
<h1>
    {{object.first_name}} {{object.last_name}} 
</h1>
<ul> 
    {% for a in object.assessment_set.all %}
        <li>{{a.standard.statement_name}}: {{a.score}}</li>
    {% empty %}
        <li>This student has no assessments</li>
    {% endfor %}
</ul>
<p>
    Active: {{object.active}}
</p>
<div class="btn-group">
    <a href="{% url "student-list" %}" class="btn btn-primary btn-sm ml-2">
        Go Back to Student List
    </a>
    <a href="{% url "student-update" pk=object.pk %}" class="btn btn-warning btn-sm ml-2">
        Edit Student
    </a>
    <a href="{% url "student-delete" pk=object.pk %}" class="btn btn-danger btn-sm ml-2">
        Delete Student
    </a>
</div>
{% endblock %}

templates/tracker/student_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">
        Save
    </button>
</form>
{% endblock %}

templates/tracker/student_list.html
{% extends "base.html" %}
{% block content %}
<h2>Students</h2>

<a class="btn btn-success btn-sm mb-3" href="{% url "student-add" %}" role="button">
  Create New Student
  <i class="bi bi-person-plus"></i>
</a>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
    </tr>
  </thead>
  <tbody>
    {% for student in object_list %}
    <tr>
      <th scope="row">
        <a href="{% url "student-detail" pk=student.pk %}">
          {{student.id}}
        </a>
      </th>
      <td>
        <a href="{% url "student-detail" pk=student.pk %}">
          {{student.first_name}}
        </a>
      </td>
      <td>
        <a href="{% url "student-detail" pk=student.pk %}">{{student.last_name}}
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}